# Docker Compose configuration for the Notes App

# This Docker Compose file defines two services: 'app' for the FastAPI application and 'db' for the PostgreSQL database.
services:

  # The 'app' service builds the FastAPI application from the current directory, maps port 8000, and sets up environment variables for database connection.
  app:
    
    # Build the Docker image for the FastAPI application using the Dockerfile in the current directory.
    build: .

    # Name of the container for the FastAPI application.
    container_name: notes_app

    # Restart the container automatically if it crashes.
    ports:
      - "8000:8000"

    # The 'app' service depends on the 'db' service, ensuring that the database is started before the application.
    depends_on:
      - db

    # Override environment variables for Docker (VERY IMPORTANT)
    environment:
      - APP_NAME=Notes Backend
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000

      # 🔥 FIX: use 'db' instead of localhost
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=notes_db
      - DB_USER=postgres
      - DB_PASSWORD=Ashu11122000@

      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

      - GOOGLE_CLIENT_ID=578024159733-civh19cpp7gkf5pes9g19qkibcke32c7.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=your_client_secret

    # Mount the current directory to /app in the container, allowing for live code 
    volumes:
      - .:/app

  # The 'db' service uses the official PostgreSQL image, sets up environment variables for the database, and maps port 5432.
  db:
    # Uses the official PostgreSQL image version 15 for the database service.
    image: postgres:15

    # Name of the container for the PostgreSQL database.
    container_name: notes_db

    # Restart the container automatically if it crashes.
    restart: always

    # Environment variables to configure the PostgreSQL database, including the username, password, and database name.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ashu11122000@
      - POSTGRES_DB=notes_db
    
    # Here, mapping port 5433 of the postgres container to port 5432 on the host machine
    ports:
      - "5433:5432"

    # Here, I will create a volume names 'Postgres_data'. This will allow us to persist the data of our database even if the container is stopped or removed.
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Defines the named volume 'postgres_data' that is used to persist the PostgreSQL database data.
volumes:
  postgres_data: